### ISSUE TITLE
Добавить корневой Makefile 

### ISSUE THREAD

**Issue by volodink** [volodink/ubx-decoder-embedded#7]
Задачи мейк файла:
1. Вызов сборки документации
2. Вызов сборки проекта
3. Вызов загрузки проекта на плату
4. Форматирование исходного кода по одному из правил
5. Очистка временных файлов проекта
...
6. Profit!

**Comment by radikalLol** [comment]
все
https://github.com/volodink/ubx-decoder-embedded/blob/master/Makefile

**Comment by radikalLol** [comment]
все
https://github.com/volodink/ubx-decoder-embedded/blob/master/Makefile
